server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: grasp-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/grasp_db
    username: grasp_user
    password: grasp_password
    driver-class-name: org.postgresql.Driver
    
  jdbc:
    template:
      query-timeout: 30
      
  security:
    jwt:
      secret: grasp-jwt-secret-key-2024-mvp-development
      expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.grasp: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
