-- Sample seed data for Grasp Study Planner development (PostgreSQL)
-- Files in docker-entrypoint-initdb.d will run automatically on first start

-- Insert sample users
INSERT INTO users (email, password_hash, first_name, last_name) VALUES
('john.doe@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'John', 'Doe'),
('jane.smith@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'Jane', 'Smith'),
('mike.wilson@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'Mike', 'Wilson');

-- Insert sample study plans
INSERT INTO study_plans (user_id, title, description, deadline, status) VALUES
(1, 'Java Programming Fundamentals', 'Complete Java programming course covering basics to intermediate concepts', '2024-12-31', 'ACTIVE'),
(1, 'Data Structures and Algorithms', 'Master core data structures and algorithmic problem solving', '2024-11-30', 'ACTIVE'),
(2, 'Web Development Bootcamp', 'Full-stack web development using React and Node.js', '2024-10-15', 'ACTIVE'),
(3, 'Machine Learning Basics', 'Introduction to machine learning concepts and Python implementation', '2024-09-30', 'PAUSED');

-- Insert sample subjects
INSERT INTO subjects (plan_id, name, difficulty_level, time_allocation_minutes, current_progress_percent) VALUES
-- Java Programming Fundamentals subjects
(1, 'Java Basics', 'BEGINNER', 1200, 25.5),
(1, 'Object-Oriented Programming', 'INTERMEDIATE', 1800, 15.0),
(1, 'Collections Framework', 'INTERMEDIATE', 900, 0.0),
(1, 'Exception Handling', 'BEGINNER', 600, 0.0),

-- Data Structures and Algorithms subjects
(2, 'Arrays and Strings', 'BEGINNER', 800, 40.0),
(2, 'Linked Lists', 'INTERMEDIATE', 1000, 20.0),
(2, 'Trees and Graphs', 'ADVANCED', 1500, 5.0),
(2, 'Sorting Algorithms', 'INTERMEDIATE', 1200, 0.0),

-- Web Development subjects
(3, 'HTML/CSS Fundamentals', 'BEGINNER', 600, 60.0),
(3, 'JavaScript ES6+', 'INTERMEDIATE', 1200, 30.0),
(3, 'React Components', 'INTERMEDIATE', 1500, 10.0),
(3, 'Node.js Backend', 'ADVANCED', 1800, 0.0),

-- Machine Learning subjects
(4, 'Python for Data Science', 'BEGINNER', 1000, 50.0),
(4, 'Statistics and Probability', 'INTERMEDIATE', 1200, 25.0),
(4, 'Linear Regression', 'INTERMEDIATE', 800, 0.0),
(4, 'Neural Networks', 'ADVANCED', 1500, 0.0);

-- Insert sample study sessions
INSERT INTO study_sessions (plan_id, subject_id, duration_minutes, completion_percent, performance_score, notes, created_at) VALUES
-- Java Programming sessions
(1, 1, 60, 80.0, 8, 'Covered variables, data types, and basic syntax', '2024-01-15 10:00:00'),
(1, 1, 45, 70.0, 7, 'Practiced loops and conditional statements', '2024-01-16 14:30:00'),
(1, 1, 90, 85.0, 9, 'Deep dive into methods and classes', '2024-01-17 09:15:00'),
(1, 2, 75, 60.0, 6, 'Introduction to OOP concepts - inheritance', '2024-01-18 16:00:00'),
(1, 2, 60, 65.0, 7, 'Polymorphism and encapsulation', '2024-01-19 11:30:00'),

-- Data Structures sessions
(2, 5, 50, 90.0, 9, 'Array manipulation and string processing', '2024-01-15 13:00:00'),
(2, 5, 40, 85.0, 8, 'Two-pointer technique practice', '2024-01-16 15:45:00'),
(2, 6, 80, 70.0, 7, 'Singly and doubly linked lists', '2024-01-17 10:30:00'),
(2, 6, 65, 75.0, 8, 'Linked list algorithms and operations', '2024-01-18 14:15:00'),

-- Web Development sessions
(3, 9, 30, 95.0, 9, 'HTML structure and semantic elements', '2024-01-15 08:00:00'),
(3, 9, 45, 90.0, 9, 'CSS styling and layout techniques', '2024-01-16 12:00:00'),
(3, 10, 60, 80.0, 8, 'ES6 features and modern JavaScript', '2024-01-17 15:30:00'),
(3, 10, 55, 75.0, 7, 'Async/await and promises', '2024-01-18 09:45:00'),
(3, 11, 70, 60.0, 6, 'React components and JSX basics', '2024-01-19 13:20:00'),

-- Machine Learning sessions
(4, 13, 50, 85.0, 8, 'NumPy and Pandas basics', '2024-01-15 11:00:00'),
(4, 13, 45, 80.0, 8, 'Data manipulation and cleaning', '2024-01-16 16:30:00'),
(4, 14, 60, 70.0, 7, 'Descriptive statistics and distributions', '2024-01-17 12:15:00'),
(4, 14, 55, 65.0, 6, 'Probability theory fundamentals', '2024-01-18 10:00:00');

-- Insert sample recommendations (generated by AI engine)
INSERT INTO recommendations (plan_id, subject_id, type, value, confidence_score, reasoning, status, created_at) VALUES
-- Recommendations for Java Programming
(1, 2, 'TIME_ADJUSTMENT', '2160', 0.85, 'Performance below 60% threshold (62.5%). Increase study time by 20% to improve learning outcomes.', 'PENDING', '2024-01-19 12:00:00'),
(1, 1, 'SCHEDULE_MODIFICATION', 'EXTEND_SESSIONS', 0.75, 'Short session durations (avg 65.0 min) may impact learning effectiveness. Consider longer, focused sessions.', 'PENDING', '2024-01-19 12:00:00'),

-- Recommendations for Data Structures
(2, 6, 'TIME_ADJUSTMENT', '1200', 0.80, 'Performance below 60% threshold (72.5%). Increase study time by 20% to improve learning outcomes.', 'PENDING', '2024-01-18 15:00:00'),

-- Recommendations for Web Development
(3, 11, 'DIFFICULTY_CHANGE', 'INTERMEDIATE', 0.90, 'Consistently high performance (87.5%) suggests ready for increased difficulty level.', 'PENDING', '2024-01-19 14:00:00'),

-- Recommendations for Machine Learning
(4, 14, 'TIME_ADJUSTMENT', '1440', 0.70, 'Performance below 60% threshold (67.5%). Increase study time by 20% to improve learning outcomes.', 'PENDING', '2024-01-18 11:00:00');

-- Update some recommendations as applied
UPDATE recommendations SET status = 'APPLIED', updated_at = '2024-01-19 13:00:00' WHERE id = 1;
UPDATE recommendations SET status = 'DISMISSED', updated_at = '2024-01-19 13:30:00' WHERE id = 2;

-- Update subject progress based on sessions
UPDATE subjects SET current_progress_percent = 25.5 WHERE id = 1;
UPDATE subjects SET current_progress_percent = 15.0 WHERE id = 2;
UPDATE subjects SET current_progress_percent = 40.0 WHERE id = 5;
UPDATE subjects SET current_progress_percent = 20.0 WHERE id = 6;
UPDATE subjects SET current_progress_percent = 60.0 WHERE id = 9;
UPDATE subjects SET current_progress_percent = 30.0 WHERE id = 10;
UPDATE subjects SET current_progress_percent = 10.0 WHERE id = 11;
UPDATE subjects SET current_progress_percent = 50.0 WHERE id = 13;
UPDATE subjects SET current_progress_percent = 25.0 WHERE id = 14;
